version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_FRONTEND_URL: ${VITE_FRONTEND_URL}
      VITE_SECRET_KEY: ${VITE_SECRET_KEY}
      VITE_ORS_KEY: ${VITE_ORS_KEY}
      NGROK_AUTH_TOKEN: ${NGROK_AUTH_TOKEN}